### ISSUE TITLE
internet won't connect / access gui?

### ISSUE THREAD

**Issue by tomburtonwood** [guysoft/FullPageOS#236]
running fullpageos for first time. i think i put the ssid and psk in the right fields in supplicant. 

i wondered if it were possible to access the gui to try to access internet via the network selection area in the top right of the top menu - at least that way i can rule out an error on my part entering info. 

is there a way to do this. 

otherwise rad - ! 

also also if i wanted to show a local file presumably putting file name like test.html in the root folder and editing the config file accordingly would work. 

thank you!

**Comment by guysoft** [comment]
ok,
1. Can you provide here your ``fullpageos-wpa-supplicant.txt`` file?
2. not possible to access the gui because the gui is what you see on screen, aka the browser. There is no desktop installed. If you want to test you can try just once to plug the Pi in to ethernet and see what is going on.
3. There is an apache web server that can serve files, you can place files in /var/www

**Comment by guysoft** [comment]
Closing if no reply

**Comment by tomburtonwood** [comment]
sorry - been swamped. i did not use Fullpage OS in the end - apologies 
for not following up.

http://tomburtonwood.com
http://twentysomethingsullivan.com
              twitter @tburtonwood
             insta @tomburtonwood

**Comment by guysoft** [comment]
Ok, closing, feel free to reopen once you get relevant information to this issue
