### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by xvilo** [guysoft/FullPageOS#253]
I would love to see my changes in a new release/build :D

**Comment by guysoft** [comment]
There isn't enough changes since the previous release to make sense for a release.
A release requires extensive testing before releasing. Its not a simple build.

What I can do is create a nightly build which would include your fix. I started one and it should upload in a few hours to the nightly build folder.

**Comment by guysoft** [comment]
online:
http://unofficialpi.org/Distros/FullPageOS/nightly/2018-09-13_2018-06-27-fullpageos-stretch-lite-0.10.0.zip
md5:
http://unofficialpi.org/Distros/FullPageOS/nightly/2018-09-13_2018-06-27-fullpageos-stretch-lite-0.10.0.zip.md5
