### ISSUE TITLE
Why Octoprint 

### ISSUE THREAD

**Issue by yOPERO** [guysoft/FullPageOS#50]
Good work indeed!

What is the reasoning behind using Octoprint as base?

Thanks,

**Comment by guysoft** [comment]
Mainly since I wrote OctoPi (not OctoPrint). FullPageOS was a result of a
weekend hackathon to prove OctoPi's build code could be used to build any
kind of custom OS.
Also I port features between them. For example next FullPageOS version
would support all Armbian distros.

Furthermore I am not aware of a decent alternative to OctoPi's build
scripts.

**Comment by yOPERO** [comment]
Thanks for the answer!
